config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :users do
    get '/profile/:nickname', to: 'users/users#profile', as: :user
  end

  root to: 'home#index'

  namespace :game do
    resources :campaigns
    resources :chapters, except: %i[index]
    resources :acts, except: %i[index]
    resources :combat_skills, except: %i[show index]
    resources :campaign_invitations, only: %i[create] do
      post '/accept', action: 'accept', on: :member, as: :accept
      post '/decline', action: 'decline', on: :member, as: :decline
    end
  end


  resources :friends, only: %i[index create] do
    get '/suggestions', action: 'suggestions', on: :collection
    delete '/decline_request', action: 'decline_request', on: :member, as: :decline_request
    patch '/accept_request', action: 'accept_request', on: :member, as: :accept_request
  end

  namespace :editor do
    get '/', to: 'editor#index'
    resources :master_characters
    resources :player_characters
    resources :enemies
    resources :main_characteristics, only: %i[update]
  end
end

app/models/enemy.rb
class Enemy < Character
  has_many :act_characters
  has_many :acts, through: :act_characters
end

app/controllers/editor/editor_controller.rb
module Editor
  class EditorController < ApplicationController
    layout 'editor/editor'
    before_action :authenticate_user!

    def index; end
  end
end

app/controllers/editor/enemies_controller.rb
module Editor
  class EnemiesController < EditorController
    before_action :set_enemy, only: %i[show edit update]

    def show; end

    def edit; end

    def update
      @enemy.update(enemy_params)

      render 'show'
    end

    def new
      @enemy = Enemy.new(enemy_params)
    end

    def create
      @enemy = Enemy.create(enemy_params)

      if enemy_params[:act_id].present?
        act = Act.find(enemy_params[:act_id])
        act.enemies << @enemy
      end
    end

    private

    def set_enemy
      @enemy = Enemy.find(params[:id])
    end

    def enemy_params
      params.require(:enemy).permit(
        :description,
        :notes,
        :name,
        :portrait,
        :campaign_id,
        :act_id
      )
    end
  end
end

app/controllers/editor/main_characteristics_controller.rb
module Editor
  class MainCharacteristicsController < GameController
    before_action :set_main_characteristic, only: %i[update]

    def update
      @main_characteristic.update(main_characteristic_params)
    end

    private

    def set_main_characteristic
      @main_characteristic = MainCharacteristic.find(params[:id])
    end

    def main_characteristic_params
      params.require(:main_characteristic).permit(
        :name,
        :value
      )
    end
  end
end

app/controllers/editor/master_characters_controller.rb
module Editor
  class MasterCharactersController < EditorController
    before_action :set_master_character, only: %i[show edit update]

    def index
      @master_characters = MasterCharacterRepository.new.user_master_characters(current_user)
    end

    def new
      @master_character = MasterCharacter.new
    end

    def update
      @master_character.update(master_character_params)

      render 'show'
    end

    def create
      @master_character = MasterCharacterRepository.new.create(master_character_params)
    end

    private

    def set_master_character
      @master_character = MasterCharacterRepository.new.find(params[:id])
    end

    def master_character_params
      params.require(:master_character).permit(
        :description,
        :notes,
        :name,
        :portrait,
        :campaign_id,
        :act_id
      )
    end
  end
end

app/controllers/editor/player_characters_controller.rb
module Editor
  class PlayerCharactersController < EditorController
    before_action :set_player_character, only: %i[show]

    def index
      @player_characters = current_user.player_characters
    end

    def show; end

    def new
      @player_character = PlayerCharacter.new
    end

    def create
      @player_character = PlayerCharacter.new(player_character_params)
      @player_character.user = current_user
      @player_character.save

      main_characteristics_params.each_pair do |code, value|
        @player_character.main_characteristics.find_by(code: code)&.update(value: value)
      end

      redirect_to @player_character
    end

    def destroy
      @player_character.destroy
    end

    private

    def player_character_params
      params.require(:player_character).permit(
        :name,
        :race_id,
        :character_class_id
      )
    end

    def main_characteristics_params
      params.require(:player_character).permit(PlayerCharacter::PERMIT_MAIN_CHARACTERISTICS)
    end

    def set_player_character
      @player_character = PlayerCharacter.find(params[:id])
    end
  end
end

app/helpers/enemies_helper.rb
module EnemiesHelper
  def new_enemy_fields
    fields = {}

    fields[:campaign_id] = {
      input: :hidden_field,
    }

    fields[:act_id] = {
      input: :hidden_field,
    }

    fields[:name] = {
      input: :text_field,
      label: 'Название'
    }

    fields[:description] = {
      input: :text_area,
      ckeditor_id: 'description_edit',
      label: 'Описание'
    }

    fields[:notes] = {
      input: :text_area,
      ckeditor_id: 'notes_edit',
      label: 'Заметки'
    }

    fields
  end
end

app/views/editor/enemies/_cards_collection.html.erb
<div class = 'container-fluid master_characters'>
  <%= turbo_stream_from 'enemies' %>

  <%= turbo_frame_tag 'enemies', class: 'row' do %>
    <% enemies.each do |enemy| %>
      <%= render partial: 'characters/card', locals: { character: enemy} %>
    <% end %>
  <% end %>

  <turbo-frame id = 'new_character'>
    <%= link_to 'Создать Врага',
                new_enemy_path(params: {
                  enemy: new_character_params
                }) %>
  </turbo-frame>
</div>

app/views/editor/enemies/_characteristics.html.erb
<div class = 'characteristics_and_portrait'>
  <div class = 'portrait'>
    <%= render partial: 'characters/character_portrait_uploader', locals: { character: enemy} %>
  </div>

  <%= turbo_stream_from 'main_characteristics' %>

  <turbo-frame id = 'main_characteristics' class = 'characteristics row'>
    <%= render enemy.main_characteristics %>
  </turbo-frame>
</div>

app/views/editor/enemies/_enemy.html.erb
<div class = 'col'> <h2><%= enemy.name %></h2></div>
<%= render partial: 'characteristics', locals: { enemy: enemy } %>
<%= render partial: 'information', locals: { enemy:enemy } %>
<%= render partial: 'skills', locals: { enemy: enemy } %>

<%= link_to 'Перейти к кампании', game_campaign_path(enemy.campaign) if enemy.campaign.present? %>

app/views/editor/enemies/_information.html.erb
<div class = 'information'>
  <div class = 'information_attributes'>
    <% record_information_attributes(enemy).each do |attribute| %>
      <%= content_tag :div,
                      class:'information__block',
                      'data-controller' => 'expand',
                      'data-expand-id' => "editor_#{attribute[:id]}",
                      'data-expand-inactive-text' => '+',
                      'data-expand-active-text' => '-' do %>
        <div class = 'd-flex justify-content-between'>
          <h5><%= attribute[:title] %></h5>
          <button class = 'btn btn-primary'
                  data-action = "expand#expand"
                  data-expand-target = 'expandButton'
          >
          </button>
        </div>

        <%= turbo_frame_tag(attribute[:name], 'data-expand-target' => 'expandValue') do %>
          <%= sanitize attribute[:text] %>

          <%= link_to 'Редактировать', edit_enemy_path(enemy) %>
        <% end %>

        <div data-expand-target = 'test'>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/editor/enemies/_skills.html.erb
<div class = 'skills'>
  <h4>Боевые умения</h4>
  <%= turbo_frame_tag 'combat_skills' do %>
    <%= render enemy.combat_skills %>
  <% end %>
</div>

app/views/editor/enemies/create.turbo_stream.erb
<%= turbo_stream.append 'enemies' do %>
  <%= render partial: 'characters/card', locals: { character: @enemy } %>
<% end %>

app/views/editor/enemies/new.html.erb
<turbo-frame id = 'new_character'>
  <h3>Новый враг:</h3>
  <%= content_tag :div, data: { controller: 'reset-form' } do %>
    <%= form_with model: @enemy,
                  data: { action: 'turbo:submit-end->reset-form#reset', 'reset-form-target' => 'form' } do |form| %>
      <% new_enemy_fields.each_pair do |field_name, field_params| %>
        <%= form.label(field_params[:label], class: 'form-label') if field_params[:label].present? %>
        <div class = 'input-group'>
          <%= form.send(field_params[:input], field_name,
                        class: 'form-control',
                        id: field_params[:ckeditor_id])
          %>
        </div>
      <% end %>

      <%= form.submit 'Создать', class: 'btn btn-success' %>
    <% end %>
  <% end %>

  <%= link_to 'Отмена', :back %>
</turbo-frame>

app/views/editor/enemies/show.html.erb
<turbo-frame id = 'body' class = 'col-9 ml-auto'>
  <div class = 'row master_character'>
    <%= render @enemy %>
  </div>
</turbo-frame>