config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  devise_for :users, controllers: {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }

  devise_scope :users do
    get '/profile/:nickname', to: 'users/users#profile', as: :user
  end

  root to: 'home#index'

  namespace :game do
    resources :campaigns
    resources :chapters, except: %i[index]
    resources :acts, except: %i[index]
    resources :combat_skills, except: %i[show index]
    resources :campaign_invitations, only: %i[create] do
      post '/accept', action: 'accept', on: :member, as: :accept
      post '/decline', action: 'decline', on: :member, as: :decline
    end
  end


  resources :friends, only: %i[index create] do
    get '/suggestions', action: 'suggestions', on: :collection
    delete '/decline_request', action: 'decline_request', on: :member, as: :decline_request
    patch '/accept_request', action: 'accept_request', on: :member, as: :accept_request
  end

  namespace :editor do
    get '/', to: 'editor#index'
    resources :master_characters
    resources :player_characters
    resources :enemies
    resources :main_characteristics, only: %i[update]
  end
end

app/models/act.rb
# frozen_string_literal: true

class Act < ApplicationRecord
  belongs_to :chapter
  has_many :act_characters
  has_many :master_characters, through: :act_characters, source: :character, class_name: 'MasterCharacter'
  has_many :enemies, through: :act_characters, source: :character, class_name: 'Enemy'

  delegate :campaign, to: :chapter

  acts_as_list scope: :chapter
end

app/controllers/game/acts_controller.rb
module Game
  class ActsController < GameController
    before_action :set_act, only: %i[show edit update]

    def show; end

    def edit; end

    def update
      @act.update(act_params)

      render 'show'
    end

    private

    def set_act
      @act = Act.find(params[:id])
    end

    def act_params
      params.require(:act).permit(
        :description,
        :notes,
        :plot
      )
    end
  end
end

app/controllers/game/campaign_invitations_controller.rb
module Game
  class CampaignInvitationsController < GameController
    before_action :set_campaign_invitation, on: %i[accept decline]

    def create
      @campaign_invitation = CampaignInvitationRepository.new.create(campaign_invitation_params)

      @campaign_invitation.send!

      render partial: 'campaign_invitation',
             locals: {
               invitation: @campaign_invitation,
               receiver: @campaign_invitation.receiver,
               campaign: @campaign_invitation.campaign
             }
    end

    def accept
      @campaign_invitation.accept!

      render partial: 'game/campaign_invitations/incoming_campaign_invitation', locals: { invitation: @campaign_invitation }
    end

    def decline
      @campaign_invitation.decline!
    end

    private

    def set_campaign_invitation
      @campaign_invitation = CampaignInvitationRepository.new.find(params[:id])
    end

    def campaign_invitation_params
      params.require(:campaign_invitation).permit(
        :sender_id,
        :receiver_id,
        :campaign_id
      )
    end
  end
end

app/controllers/game/campaigns_controller.rb
# frozen_string_literal: true

module Game
  class CampaignsController < GameController
    before_action :set_campaign, only: %i[show update edit]

    def index
      @campaigns = current_user.campaigns.includes(:master_characters, :chapters).all
    end

    def show; end

    def edit; end

    def update
      @campaign.update(campaign_params)

      render 'show'
    end

    private

    def campaign_params
      params.require(:campaign).permit(:description, :history, :notes)
    end

    def set_campaign
      @campaign = Campaign.find(params[:id])
    end
  end
end

app/controllers/game/chapters_controller.rb
# frozen_string_literal: true

module Game
  class ChaptersController < GameController
    before_action :set_chapter, only: %i[show edit update]

    def show; end

    def edit; end

    def update
      @chapter.update(chapter_params)

      render 'show'
    end

    def new
      @chapter = Chapter.new(chapter_params)
    end

    def create
      @chapter = Chapter.create(chapter_params)

      respond_to do |format|
        format.html { render partial: 'game/campaigns/plot', locals: { campaign: @chapter.campaign } }
      end
    end

    private

    def chapter_params
      params.require(:chapter).permit(
        :name,
        :description,
        :notes,
        :campaign_id
      )
    end

    def set_chapter
      @chapter = Chapter.find(params[:id])
    end
  end
end

app/controllers/game/combat_skills_controller.rb
module Game
  class CombatSkillsController < GameController
    before_action :set_combat_skill, only: %i[edit update]

    def edit; end

    def update
      @combat_skill.update(combat_skill_params)

      render @combat_skill
    end

    def new
      @combat_skill = CombatSkill.new(combat_skill_params)
    end

    def create
      @combat_skill = CombatSkill.create(combat_skill_params)
    end

    private

    def set_combat_skill
      @combat_skill = CombatSkill.find(params[:id])
    end

    def combat_skill_params
      params.require(:combat_skill).permit(
        :description,
        :damage,
        :character_id,
        :hit_modifier,
        :name
      )
    end
  end
end

app/controllers/game/game_controller.rb
module Game
  class GameController < ApplicationController
    layout 'game/game'
    before_action :authenticate_user!
  end
end

app/helpers/acts_helper.rb
module ActsHelper
end

app/views/game/acts/_act.html.erb
<%= turbo_frame_tag dom_id(act),
                    class: 'act_block',
                    data: {
                      controller: 'expand',
                      'expand-inactive-text' => '+',
                      'expand-active-text' => '-'
                    } do %>
  <div class = 'd-flex justify-content-between'>
    <%= link_to(game_act_path(act), 'data-turbo-frame' => "_top") do %>
      <h5><%= "Акт #{act.position}. #{act.name}"%></h5>
    <% end %>

    <button class = 'btn btn-primary'
            data-expand-target = 'expandButton'
            data-action = "expand#expand"
    >
    </button>
  </div>

  <div data-expand-target = 'expandValue'>
    <%= sanitize act.description %>
  </div>
<% end %>

app/views/game/acts/_information.html.erb
<div class = 'information'>
  <% record_information_attributes(act).each do |attribute| %>
    <div class = 'information__block'
         data-controller = 'expand'
         data-expand-inactive-text = '+'
         data-expand-active-text = '-'
    >
      <div class = 'd-flex justify-content-between'>
        <h5><%= attribute[:title] %></h5>
        <button class = 'btn btn-primary'
                data-action = "expand#expand"
                data-expand-target = 'expandButton'
        >
        </button>
      </div>

      <%= turbo_frame_tag(attribute[:name], 'data-expand-target' => 'expandValue') do %>
        <%= sanitize attribute[:text] %>

        <%= link_to 'Редактировать', edit_game_act_path(act) %>
      <% end %>
    </div>
  <% end %>


  <%= link_to 'Перейти к главе', game_chapter_path(act.chapter), 'data-turbo-frame'=>"_top" %>
</div>

app/views/game/acts/_plot.html.erb
<div class = 'plot'>
  <turbo-frame id = 'plot'>
    <%= sanitize act.plot %>

    <%= link_to 'Редактировать', edit_game_act_path(act) %>
  </turbo-frame>
</div>

app/views/game/acts/edit.html.erb
<% record_information_attributes(@act).each do |attribute| %>
  <%= turbo_frame_tag attribute[:name] do %>
    <%=form_with(model: [:game, @act]) do |form| %>
      <%= content_tag :div,
                      'data-controller' => 'ckeditor',
                      'data-ckeditor-id' => "#{attribute[:id]}" do%>
        <div class = 'input-group mb-1 mt-2'>
          <%= form.send(attribute[:type], attribute[:name], rows: 10, id: "#{attribute[:id]}") %>
        </div>

        <div class = 'input-group mb-1 mt-2'>
          <%= form.submit 'Сохранить', class: 'btn btn-primary'%>
        </div>
      <% end %>
    <% end %>
  <% end %>
<% end %>

<%= turbo_frame_tag 'plot' do %>
  <%=form_with(model: [:game, @act]) do |form| %>
    <%= content_tag :div,
                    'data-controller' => 'ckeditor',
                    'data-ckeditor-id' => "plot_editor" do%>
      <div class = 'input-group mb-1 mt-2'>
        <%= form.text_area :plot, rows: 10, id: "plot_editor" %>
      </div>

      <div class = 'input-group mb-1 mt-2'>
        <%= form.submit 'Сохранить', class: 'btn btn-primary'%>
      </div>
    <% end %>
  <% end %>
<% end %>

app/views/game/acts/show.html.erb
<turbo-frame id = 'body' class = 'col-9 ml-auto'>
  <div class = 'row chapter'>
    <div class = 'col'> <h2><%= @act.name %></h2></div>
    <%= render partial: 'information', locals: { act: @act} %>

    <div class = 'col'> <h3>Сюжет</h3></div>
    <%= render partial: 'plot', locals: { act: @act} %>

    <div class = 'col'><h3>Персонажи акта</h3></div>
    <%= render partial: 'characters/characters_block',
               locals: {
                 act: @act,
                 campaign: @act.campaign,
                 master_characters: @act.master_characters,
                 enemies: @act.enemies
               } %>
  </div>
</turbo-frame>